### ISSUE TITLE
files should not be downloaded during build

### ISSUE THREAD

**Issue by bentley** [valhalla/baldr#216]
Since a9dff046222d72e227535bbf84c60339244ba6fe the `date_time_zonespec.h` header is generated from a file downloaded at build time.

Performing network operations during a build is problematic. OpenBSD’s package build machines run builds as an unprivileged user with no network access for security reasons. It would be good to come up with some alternative method for generating this header.

**Comment by kevinkreiser** [comment]
yeah we were kind of waffling over this approach, the thought was that currently you'd need the internet to even get valhalla to install it, but i could see if it were bundled with a distribution how that wouldnt be the case. we'll look at a way to just keep this file statically.

**Comment by kevinkreiser** [comment]
this is fixed!
