### ISSUE TITLE
Out-of-bound coordinates results in invalid tile id

### ISSUE THREAD

**Issue by ptpt** [valhalla/baldr#334]
When input coordinates are out of longtitude,latitude bounds, meili says it gets invalid tile ids.
```
6 2017/01/08 11:23:14.297012 POST /mm/?mode=multimodal&search_radius= HTTP/1.0
2017/01/08 11:23:14.297466 [INFO] Got Map Matching Request 6
2017/01/08 11:23:14.297685 [ERROR] src/prime_server.cpp:430 worker_t: Tile id out of valid range
```

Diving into the code, I found that errors were reported here https://github.com/valhalla/meili/blob/master/src/meili/candidate_search.cc#L199-L200

Maybe baldr should do some work to normalize out-of-bound coordinates to [-180,180] and [-90,90], or at least let `GetGraphTile` return nullptr when it sees out-of-bound coordinates?

**Comment by kevinkreiser** [comment]
this is very strange `GetGraphTile` should indeed return `nullptr` when it gets invalid ids. Anyway this will be an easy test to write i think.

**Comment by dnesbitt61** [comment]
It is probably the one with PointLL. This line:

   id.Set(static_cast<int32_t>(tl->second.tiles.TileId(pointll)), level, 0);

calls Tiles which returns -1 if the tile row or col is out of bounds (which likely happens for PointLL out of range).

**Comment by kevinkreiser** [comment]
right but once it has made the bogus id doesnt it then call the other one with the id and then fail to find it?
