### ISSUE TITLE
GetGraphTile should return nullptr if graphid is invalid

### ISSUE THREAD

**Issue by ptpt** [valhalla/baldr#338]
```c++
const GraphTile* GraphReader::GetGraphTile(const GraphId& graphid);
```

invalid graphid will trigger:

```
2017/01/22 17:36:58.100516 [ERROR] src/prime_server.cpp:430 worker_t: Could not compute FileSuffix for non-existent level
```

**Comment by ptpt** [comment]
Relates to https://github.com/valhalla/meili/pull/72/commits/d70a64a33163066a04ff0224576a2c7e0fadef4b

**Comment by kevinkreiser** [comment]
in the commit you linked to you have this bit of code `pred_edgeid.Is_Valid()` before you go to use `pred_edgeid` to access tiles. my question is, if its not "invalid" then it must be initialized to some crazy value (ie not default initialized because default they initialize to invalid). not sure what is going on here but it seems to be a bug in the edge label ids in that bit of code?

**Comment by ptpt** [comment]
In that code, the `pred_edgeid.Is_Valid()` prevents `isTransition` from sending the invalid edgeid to `GraphReader::GetGraphTile`. However if `GraphReader::GetGraphTile` returns nullptr for invalid edgeids, then `isTransition` will return false instead of reporting error.

Despite the commit, don't you think `GraphReader::GetGraphTile` should return nullptr when getting invalid graph id?

**Comment by kevinkreiser** [comment]
yes that is what i was saying. i cant understand how `GetGraphTile` was getting an "invalid" id  due to that check. are you saying that you added that check after you started getting that annoying message? sorry for the misunderstanding!

**Comment by ptpt** [comment]
No, sorry. I mean before this commit, I got that error message (that's not just annoying, but also made mm refused to work). After this commit, the issue fixed. However, I think this should be fixed in baldr, i.e. let `GetGraphTile` return null when it gets invalid graphid.

**Comment by dnesbitt61** [comment]
let me test performance. I've been relying on code in thor to make sure not to call GetGraphTile if there is an invalid tile (which can't really occur from Valhalla graph tiles that have been validated! and is only needed when back tracking predecessor edges)

**Comment by ptpt** [comment]
Sorry again my wrong wording. It's not a bug in `GetGraphTile`, it is just a suggestion that maybe it'd better return nullptr for non-existing graphid or the invalid graphid.
